config/routes.rb
WinnemacSite::Application.routes.draw do
  resources :spaces, except: [:new, :create, :destroy, :show]
  resources :units, except: [:new, :create, :destroy]
  resources :users, only: [:new, :create]
  resources :contact, only: [:new, :create]

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  root 'static_pages#index'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :name, :email, :phone, :subject, :message, presence: true
  validates_format_of :email, with: VALID_EMAIL_REGEX
end

app/models/image.rb
class Image < ActiveRecord::Base
	belongs_to :unit
end

app/models/space.rb
class Space < ActiveRecord::Base
end

app/models/unit.rb
class Unit < ActiveRecord::Base
	has_many :images
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validate :only_one

  def only_one
    errors.add(:base, 'Cannot add another user. Not authorized.') if User.count > 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :find_user
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected
    def find_user
      if session[:user_id] != nil
        @user = User.find_by(id: session[:user_id])
      else
        @user = nil
      end
    end

    def authorize
      unless User.find_by(id: session[:user_id])
        redirect_to root_url
      end
    end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def new
    @message = Contact.new
  end

  def create
    @message = Contact.new(message_params)
    if @message.save
      ContactMailer.delay.contact_email(@message.id)
      redirect_to root_path, notice: "Form Submitted"
    else
      render action: 'new'
    end
  end

  private
    def message_params
      params.require(:contact).permit(:name, :email, :subject, :message, :phone)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # Logs a user in
  def create
    user_login = params[:login].downcase
    user = User.find_by(login: user_login)
    if user and user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url
    else
      redirect_to login_url, alert: "Invalid user/password combination"
    end
  end

  def destroy
    reset_session
    redirect_to root_url , notice: "Logged out"
  end
end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
  before_action :set_space, only: [:show, :edit, :update]
  before_action :authorize, only: [:edit, :update]

  # GET /spaces
  def index
    if @user.nil?
      @spaces = Space.where(available:true).order(:id)
    else
      @spaces = Space.all.order(:id)
    end
  end

  # PATCH/PUT /spaces/1
  def update
    if @space.update(space_params)
      redirect_to spaces_url, notice: 'Space was successfully updated.'
    else
      render action: 'edit'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_space
      @space = Space.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def space_params
      params.require(:space).permit(:title, :name, :description, :image_url, :price, :available)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :set_unit, only: [:show, :edit, :update]
  before_action :authorize, only: [:edit, :update]

  # GET /units
  def index
    if @user.nil?
      @units = Unit.where(available:true).order(:id)
    else
      @units = Unit.all.order(:id)
    end
  end

  # GET /units/1
  def show
    redirect_to units_url, notice: 'Unit not available' unless @unit.available || @user
  end

  # PATCH/PUT /units/1
  def update
    if @unit.update(unit_params)
      redirect_to @unit, notice: 'Unit was successfully updated.'
    else
      render action: 'edit'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unit_params
      params.require(:unit).permit(:title, :price, :available, :description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: 'User was successfully created.'
    else
     render action: 'new'
    end
  end

  private
    def user_params
      params.require(:user).permit(:login, :password, :password_confirmation, :user_type)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/spaces_helper.rb
module SpacesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contact/_form.html.erb
<%= form_for @message, url: '/contact', html: {class: "form-horozontal col-md-8"} do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "control-label"%><br>
    <%= f.text_field :name, class: "form-control", required: true %>
  </div>
  <div class="form-group">
    <%= f.label :email, class: "control-label"%><br>
    <%= f.text_field :email, class: "form-control", required: true %>
  </div>
  <div class="form-group">
    <%= f.label :phone, class: "control-label"%><br>
    <%= f.text_field :phone, class: "form-control", required: true %>
  </div>
  <div class="form-group">
    <%= f.label :subject, class: "control-label"%><br>
    <%= f.text_field :subject, class: "form-control", required: true %>
  </div>
  <div class="form-group">
    <%= f.label :message, class: "control-label"%><br>
    <%= f.text_area :message, rows: 5, class: "form-control", required: true %>
  </div>
  <div class="actions">
    <%= f.submit 'Send Message' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>2433 W Winnemac, Chicago, IL 60625</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1">

</head>
<body>
  <div class="container">
   <div class="navbar navbar-inverse" role="navigation">
     <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
         <span class="sr-only">Toggle navigation</span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">2433 W Winnemac Ave</a>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
         <li><a href="/contact/new">Contact</a></li>
         <li><a href="/spaces">Parking</a></li>
         <li><%= link_to "Units", units_path %></li>
            <% if @user %>
              <li><%= button_to "logout", logout_path , class: "btn btn-danger", method: :delete %> </li>
            <% end %>
        </ul>
      </div><!--/.nav-collapse -->
     </div><!--/.container-fluid -->
   </div>
    <% if notice.present? %>
      <div id="notice-alert" class="alert alert-dismissable alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= notice %>
      </div>
      <script type="text/javascript">
        setTimeout(function() {
          $("#notice-alert").fadeOut();
        }, 5000);
      </script>
    <% end %>

    <% if @user %>
      <p>
        You are logged in as <%= @user.login %>
      </p>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/spaces/_form.html.erb
<%= form_for(@space) do |f| %>
  <% if @space.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@space.errors.count, "error") %> prohibited this space from being saved:</h2>

      <ul>
      <% @space.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :available %><br>
    <%= f.check_box :available %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/spaces/edit.html.erb
<h1>Editing space</h1>

<%= render 'form' %>

<%= link_to 'Show', @space %> |
<%= link_to 'Back', spaces_path %>

app/views/spaces/index.html.erb
<h1>Listing available spaces</h1>
<% @spaces.each do |space| %>

<div class="row">
  <div class="col-md-4">
    <%= image_tag(space.image_url, :alt => "property_photo", class: "preview-image") %>
  </div>
  <div class="col-md-8">
    <h2><%=space.title%></h2>
    <h4><%= number_to_currency(space.price)%></h4>
    <p><%=space.description%></p>
    <% if @user %>
      <p>SPOT ID: <%= space.id %> </p>
      <p>AVAILABLE: <%= space.available %> </p>
    <% end %>
  </div>
</div>

<hr>

<%end%>

<% if @spaces.count == 0%>
  <h3>There are no spaces available</h3>
<% end %>

app/views/static_pages/index.html.erb
<div class="jumbotron">
  <h1>Parking Available</h1>
  <p>Two off street parking spaces availble now!</p>
  <%= link_to('Learn More', spaces_path , class: 'btn btn-primary btn-lg') %>
</div>

<div id="main-image-container">
  <%= image_tag('ext_front.png', :alt => "property_photo", class: "main-image") %>
</div>

app/views/units/_form.html.erb
<%= form_for(@unit) do |f| %>
  <% if @unit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@unit.errors.count, "error") %> prohibited this unit from being saved:</h2>

      <ul>
      <% @unit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :available %><br>
    <%= f.check_box :available %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/units/edit.html.erb
<h1>Editing unit</h1>

<%= render 'form' %>

<%= link_to 'Show', @unit %> |
<%= link_to 'Back', units_path %>

app/views/units/index.html.erb
<h1>Listing available units:</h1>

<% @units.each do |unit| %>

<div class="row">
  <div class="col-md-4">
   <% image = unit.images.where(main: true).first %>
   <% if !image.nil? %>
    <%= link_to(image_tag(image.image_url, :alt => "property_photo", class: "preview-image"),unit_path(unit)) %>
  <% else %>
    <%= link_to(image_tag('ext_front.png', :alt => "property_photo", class: "preview-image"), unit_path(unit)) %>
  <% end %>
  </div>
  <div class="col-md-8">
    <h2><%=unit.title%></h2>
    <h4><%= number_to_currency(unit.price)%></h4>
  </div>
</div>

<hr>

<%end%>

<% if @units.count == 0%>
  <h3>There are no units available</h3>
<% end %>

app/views/units/show.html.erb
<p id="notice"><%= notice %></p>

<div class="page-header">
  <a class="application-link" href="https://www.rentapplication.net/2433winnemac/">Apply Online Now</a>
  <div class="custom-title">
    <%= @unit.title + ' | ' + @unit.subtitle %>
  </div>
</div>

<div class="unit-price">
	<%= number_to_currency(@unit.price, precision: 0) %>
</div>

<div class="unit-description">
	<%= @unit.description.html_safe %>
</div>

<div id="slider1_container">
  <!-- Slides Container -->
  <div u="slides" class="slides-container">
    <% @unit.images.each do |image| %>
      <div>
        <%= image_tag image.image_url, class: 'resized-image' %>
        <div class="image-caption" u="caption" t="L-R">
          <!-- Any HTML Content Here -->
          <%= image.description %>
        </div>
      </div>
    <% end %>
  </div>
  <span u="arrowleft" class="jssora02l" style="width: 55px; height: 55px; top: 300px; left:0;"></span>
  <span u="arrowright" class="jssora02r" style="width: 55px; height: 55px; top: 300px; right:0;"></span>

  <div u="navigator" class="jssorb01" style="bottom: 16px; right: 10px;">
      <!-- bullet navigator item prototype -->
      <div u="prototype"></div>
  </div>
</div>

<script>
  jQuery(document).ready(function ($) {
    var _CaptionTransitions = [];
    //Left to Right
    _CaptionTransitions["L-R"] = { $Duration: 800, $FlyDirection: 1 };
    //Right to Left
    _CaptionTransitions["R-L"] = { $Duration: 800, $FlyDirection: 2 };
    //Top to Bottom
    _CaptionTransitions["T-B"] = { $Duration: 800, $FlyDirection: 4 };
    //Bottom to Top
    _CaptionTransitions["B-T"] = { $Duration: 800, $FlyDirection: 8 };

    var options = {
      $HWA: false,
      $AutoPlay: true,
      $AutoPlayInterval: 4000,
      $PauseOnHover: 1,
      $ArrowKeyNavigation: true,
      $ArrowNavigatorOptions: {
        $Class: $JssorArrowNavigator$,
        $ChanceToShow: 2,
        $AutoCenter: 2,
        $Steps: 1,
        $Scale: false
      },
      $BulletNavigatorOptions: {
        $Class: $JssorBulletNavigator$,
        $ChanceToShow: 2,  //[Required] 0 Never, 1 Mouse Over, 2 Always
        $AutoCenter: 1,  //[Optional] Auto center navigator in parent container, 0 None, 1 Horizontal, 2 Vertical, 3 Both, default value is 0
        $Steps: 1,
        $Lanes: 1,
        $SpacingX: 5,
        $SpacingY: 4,
        $Orientation: 1,  //[Optional] The orientation of the navigator, 1 horizontal, 2 vertical, default value is 1
        $Scale: false //Scales bullets navigator or not while slider scale
      },
      $CaptionSliderOptions: {
        $Class: $JssorCaptionSlider$,
        $CaptionTransitions: _CaptionTransitions,
        $PlayInMode: 1,
        $PlayOutMode: 3
      }
    };
    var jssor_slider1 = new $JssorSlider$('slider1_container', options);

     //responsive code begin
        //you can remove responsive code if you don't want the slider scales
        //while window resizes
        function ScaleSlider() {
            var parentWidth = $('#slider1_container').parent().width();
            if (parentWidth) {
              if (parentWidth < 768) {
                console.log('first');
                jssor_slider1.$ScaleWidth(parentWidth);
              } else {
                console.log('two');
                jssor_slider1.$ScaleWidth(parentWidth * 0.75);
              }
            }
            else
                window.setTimeout(ScaleSlider, 30);
        }
        //Scale slider after document ready
        ScaleSlider();

        //Scale slider while window load/resize/orientationchange.
        $(window).bind("load", ScaleSlider);
        $(window).bind("resize", ScaleSlider);
        $(window).bind("orientationchange", ScaleSlider);
        //responsive code end
  });
</script>
<% if @user  %>
  <%= link_to 'Edit', edit_unit_path(@unit) %> |
<% end %>
<%= link_to 'Back', units_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :login %><br>
    <%= f.text_field :login %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :user_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/new.html.erb
<%= render 'form' %>